version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: '1234'
    command:
      - createdb -U postgres estoque_dbe
    ports:
      - "5433:5432"
    restart: unless-stopped
