spring:
  profiles:
    active: jwt
  datasource:
    url: jdbc:postgresql://localhost:5433/estoque_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: DEBUG
